### ISSUE TITLE
Shortcode Gallery++ doesn't work with the Gantry 5 Helium theme

### ISSUE THREAD

**Issue by garned** [sal0max/grav-plugin-shortcode-gallery-plusplus#1]
Grav v1.7.5, Gantry v5.4.37

It seems like jQuery as well as the plugin specific JS and CSS files aren't being included.
I got it working by adding the following into /user/plugins/gantry5/engines/nucleus/templates/page_head.html.twig, which isn't very elegant but the best I could come up with.

```
 <script src="//code.jquery.com/jquery-3.1.1.min.js" type="text/javascript"></script>
 <script src="http://mysite.com/grav/user/plugins/shortcode-gallery-plusplus/vendor/glightbox/glightbox.min.js" type="text/javascript"></script>
  <script src="http://mysite.comh/grav/user/plugins/shortcode-gallery-plusplus/vendor/justified-gallery/jquery.justifiedGallery.min.js" type="text/javascript"></script>
  <link rel="stylesheet" href="http://mysite.com/grav/user/plugins/shortcode-gallery-plusplus/vendor/glightbox/glightbox.min.css">
  <link rel="stylesheet" href="http://mysite.com/grav/user/plugins/shortcode-gallery-plusplus/vendor/justified-gallery/justifiedGallery.min.css">
```
right before
```
{% block head_application -%}
        {{ gantry.styles('head')|join("\n")|raw }}
        {{ gantry.scripts('head')|join("\n")|raw }}
{%- endblock %}
```

Thank you for your work!
Tobias

**Comment by sal0max** [comment]
Thanks a lot for the bug report!

I indeed missed, that Justified-Gallery depends on jQuery.
It is added now in bugfix version 1.0.2

I don't see a problem with the JS and CSS files. Could you test and report, please?

**Comment by garned** [comment]
Thanks for the quick response and fix! It seems to work fine now without my changes to the twig file.

**Comment by NK74** [comment]
What's the workaround ?

**Comment by sal0max** [comment]
> What's the workaround ?

No workaround needed. Just use the latest version of the plugin.
