### ISSUE TITLE
[question] shortcode in twig template

### ISSUE THREAD

**Issue by fugo** [sal0max/grav-plugin-shortcode-gallery-plusplus#11]
I want to use your gallery shortcode in a twig.html – is it possible?
I thought it should be 
```
{{% gallery %}}
{{ image["image"]|raw }}
{{% end %}}
```

TIA

**Comment by sal0max** [comment]
Hi,

Twig integration is provided via the grav-plugin-shortcode-core plugin. See here:
https://github.com/getgrav/grav-plugin-shortcode-core#using-shortcodes-in-twig

So, the correct syntax for this shortcode-gallery-plusplus plugin  would be:

```twig
{{ "[gallery]
   <img src=\"https://picsum.photos/400/600\" alt=\"\"></img>
   <img src=\"https://picsum.photos/600/400\" alt=\"\"></img>
[/gallery]"|shortcodes|raw }}
```

Notice, that the images already have to be in their html form, not as image shortcode (`![](image.jpg)`).

Does this help?

**Comment by fugo** [comment]
Thank you but I need this for images inserted in the front end.

**Comment by sal0max** [comment]
I don't know what to say anymore. You wanted to know how to use this plugin with twig. I told you how to do it.
So I'll close this for now.

**Comment by hughbris** [comment]
@sal0max 
> Notice, that the images already have to be in their html form

I just found your important instructions looking for why my nested shortcode version didn't load in Twig.

Could you put the requirement to include `<img>` tags as HTML in the README please? Including a short section on including with Twig with your example would be ideal.

Cheers :+1:

**Comment by sal0max** [comment]
Currently I've limited to no time for this plugin, @hughbris. So, you're welcome to create a pull request for that matter, if it's still of concern.

**Comment by hughbris** [comment]
Thanks for letting me know and totally understandable. I'm not actually using this plugin any more but I will consider adding this in future.
