### ISSUE TITLE
Going to top of website when opening gallery on mobile device

### ISSUE THREAD

**Issue by bartoszwanot** [sal0max/grav-plugin-shortcode-gallery-plusplus#19]
Hi!
I've fund a bug that can be annoying for people reading articles on mobile devices (smartphone).

When you open the gallery with images, the whole website is scrolling back to the top in the background, so when the user is closing the gallery he needs to scroll down to the place when he was reading.  Tested on Samsung Galaxy S10e device with latest Chrome and Samsung's stock web browser, but you can see the same behavior on Chrome or Edge when emulating mobile device in DevTools.

You can check such behavior here on my website: https://nindyki.pl/instax-mini-link-recenzja (which runs on Grav  v1.7.20).

**Comment by sal0max** [comment]
I can't reproduce that behavior in my sites.
Here's another user of this plugin: https://eduardomataicasa.com/en/artworks
The issue you mention doesn't happend there, either.

**Comment by bartoszwanot** [comment]
Yeah, on that website it works without problem. But on my site something is wrong... Any idea what can be the cause?

**Comment by bartoszwanot** [comment]
Okay, thanks to my friend I've found the cause of such behavior - it was fault of CSS for sticky-footer class, where height was set to 100%. By removing it there is no problem with it. I'm closing this issue in such case.

**Comment by sal0max** [comment]
Thanks for the update!
Can be helpful to others.

Cheers!
