### ISSUE TITLE
"justified-gallery" disappeard after recent update of Shortcode Gallery++ v1.2.1

### ISSUE THREAD

**Issue by tangr04** [sal0max/grav-plugin-shortcode-gallery-plusplus#22]
Hello!

After the recent update of Shortcode Gallery++ (v1.2.1) my images are not arranged as justified gallery anymore. 

I have updated the plugin on a test-website first and it shows a different arrangement of my images, than on the website which is online. After opening the inspector and comparing both portfolios, it shows that the class="justified-gallery" is not there anymore on the test-site.

this is the website where it works correctly (I haven´t updated the plugin here): https://www.lexart-tattoo.at/

How can I fix this on my test site?

Thanks a lot in advance.

![Shortcode-Gallery-after-update](https://user-images.githubusercontent.com/92982288/139061508-6ae14bdb-d7bc-4948-8b84-e956ba291bb4.PNG)
![Shortcode-Gallery-before-update](https://user-images.githubusercontent.com/92982288/139061514-d57af030-a805-4436-9899-d81f527b478a.PNG)

**Comment by beamaria** [comment]
@sal0max Hi I have the same problem with Helium:  the class="justified-gallery" is not there anymore.

My settings:
Shortcode gallery+++ v 1.2.1
Helium v 5.5.11
Gantry 5 v 5.5.11
Grav v.1.7.30
Admin Panel v. 1.10.30.2

I tried to locate the base.html.twig file of the theme, but i couldn't find it

Any idea how to fix the issue?
