### ISSUE TITLE
Request: the ability to control the character limit of the description in mobile views

### ISSUE THREAD

**Issue by oceanclr** [sal0max/grav-plugin-shortcode-gallery-plusplus#26]
Currently you'd have to click "See more" on mobile views
A request to have the ability to control the limit of the characters
Again, thank you for sharing the code

![grav-shorcode-gallery](https://user-images.githubusercontent.com/104034088/166824145-c328fb84-eb25-46cd-a0c8-617bfeb4f714.png)

**Comment by sal0max** [comment]
Implemented in version 1.4.0.
The number of characters until "See more" appears and also what text to use instead of "See more" can be configured in the plugins options menu.

**Comment by sal0max** [comment]
-> 2e7575da594cf14e4c20878a164f28cefeeac5e3
