### ISSUE TITLE
Justify first instead of last row when odd number of images

### ISSUE THREAD

**Issue by godfatherjohn** [sal0max/grav-plugin-shortcode-gallery-plusplus#30]
First of all, thank you very much for this marvellous plugin! It comes in very handy and clearly does the job! 

This is a feature request. 

Currently, when `justify` is enabled and the number of images is odd, the last image is displayed big. Example:

| 1st image | | 2nd image|
|     T h i r d _____  i m a g e   |

The thing is, it would be much nicer to display the first image bigger and the others smaller, hence the other way around.

|     F i r s t  _____   i m a g e   |
| 2nd image | | 3rd image|

**Comment by sal0max** [comment]
Great idea!

Sadly, that's not a feature this plugin can provide. As stated in the README, this Grav plugin internally uses [Justified-Gallery](https://github.com/miromannino/Justified-Gallery) by Miro Mannino. You can look for yourself, but I couldn't find an option to make the first row justified: https://miromannino.github.io/Justified-Gallery/options-and-events/

You could propose the feature request to that project.
