### ISSUE TITLE
Separate row height for smartphone/mobile devices

### ISSUE THREAD

**Issue by godfatherjohn** [sal0max/grav-plugin-shortcode-gallery-plusplus#31]
It would be nice to have a separate option to determine the row height for mobile devices. The reason being that an array of images looks good on the desktop but on the phone it simply is one image (full width of screen) per row.

My current workaround is to keep the row height at 100px, this way it is two images per row on a phone and six images per row on the desktop. It is not optimal but I can live with it. It would be nicer to only have 3 per row on the desktop.

**Comment by sal0max** [comment]
Same as in #30 : Great idea, but nothing this Grav plugin could achieve. [Justified-Gallery](https://github.com/miromannino/Justified-Gallery) by Miro Mannino has to provide this setting first.
