### ISSUE TITLE
Uncaught TypeError: this.resetImgSrc is not a function

### ISSUE THREAD

**Issue by bartoszwanot** [sal0max/grav-plugin-shortcode-gallery-plusplus#38]
Hi there!

Recently I've got some problems with your plugin on my site with Quark Open Publishing theme.

When I use it, images on page are blank (but I can see captions) and when I click on them - they will show correctly. In Chrome's console I can see such error:
`Uncaught TypeError: this.resetImgSrc is not a function`

You can check how it looks and behave for example here: https://nindyki.pl/dorfromantik-nintendo-switch

Any idea how to fix it?

**Comment by sal0max** [comment]
Definitely happening inside the [miromannino/Justified-Gallery](https://github.com/miromannino/Justified-Gallery) dependency.
Seems to be this bug: https://github.com/miromannino/Justified-Gallery/issues/333

Sorry I can't help any further.

**Comment by bartoszwanot** [comment]
Thanks for the reply @sal0max . But the strangest thing is that it was working like a month or so and now it's broken :/

**Comment by bartoszwanot** [comment]
Ok, found the solution - in main configuration of Grav CMS in _Media_  tab you need to change value of _Image loading behavior_ to **Eager** (I had Lazy turned on).

**Comment by frankfarm** [comment]
I encountered this problem, and using ?loading=eager in my markdown on the images did not resolve the problem but the commit at [73fb2fcda949e67abcd4cc84dfe1518e5a86df26](https://github.com/miromannino/Justified-Gallery/pull/390/changes/73fb2fcda949e67abcd4cc84dfe1518e5a86df26) did resolve it. Could this fix please be included in future releases of shortcode-gallery-plus-plus?
