### ISSUE TITLE
Pinch to zoom

### ISSUE THREAD

**Issue by hermanncoders** [sal0max/grav-plugin-shortcode-gallery-plusplus#40]
Thank you so much for this plugin!

Are you planning on implementing pinch to zoom on mobile devices? Or have we overseen the option?

Thanks again!

**Comment by sal0max** [comment]
This plugin is merely a wrapper for [Justified-Gallery](https://github.com/miromannino/Justified-Gallery) by Miro Mannino and [GLightbox](https://github.com/biati-digital/glightbox) by biati digital.
If a feature is missing, you have to look there.

In your case, you'd probably look here: https://github.com/biati-digital/glightbox/issues/315
