### ISSUE TITLE
Group multiple galleries

### ISSUE THREAD

**Issue by francoisjacquet** [sal0max/grav-plugin-shortcode-gallery-plusplus#41]
Hello,

Thank you for this neat plugin :)

I would like to be able to group multiple separate galleries, so users can navigate through all the images which are spread across the page.

For example, being able to navigate between the 3 images in the following 3 galleries:
```md
### Title 1

Text 1.

[gallery]
![image 1](image1.png)
[/gallery]

### Title 2

Text 2.

[gallery]
![image 2](image2.png)
[/gallery]

### Title 3

Text 3.

[gallery]
![image 3](image3.png)
[/gallery]
```

Is this something doable?

**Comment by sal0max** [comment]
I don't think that's possible. Would be something [Justified Gallery](https://miromannino.github.io/Justified-Gallery/) would have to provide.
