### ISSUE TITLE
Don't work

### ISSUE THREAD

**Issue by softyoda** [sal0max/grav-plugin-shortcode-gallery-plusplus#7]
I don't know the origine of the cause, but it don't work with my custom theme.

Screenshoot1 without the [gallery] : 
![1072_firefox_Projet_C__amcgi_-_Mozilla_Firefox_31_03_2021_21h03(2598x1648)_X3SY](https://user-images.githubusercontent.com/13988751/113198004-ad31b400-9265-11eb-8586-801eb47aaac8.jpg)

Screenshoot2 with the [gallery] : 
![1073_firefox_Projet_C__amcgi_-_Mozilla_Firefox_31_03_2021_21h04(2571x1743)_Mywf](https://user-images.githubusercontent.com/13988751/113198051-bde22a00-9265-11eb-9532-e3cc12e02ed6.jpg)

**Comment by sal0max** [comment]
HTML code that is generated looks fine.

What version of the plugin are you using?
Is Javascript enabled in your browser?

What happens when you add more images to the gallery?
What happens when you decrease the row height like so: `[gallery rowHeight=100]`?

**Comment by sal0max** [comment]
No response from @softyoda . So closing this.
