### ISSUE TITLE
how to align gallery horizontally?

### ISSUE THREAD

**Issue by lustyffh** [sal0max/grav-plugin-shortcode-gallery-plusplus#9]
Hello,

is there way to align gallery horizontally on the page? I.e. I have a gallery of just two pictures which doesn't take the full width of the page. I've tried to wrap [gallery] in `<center>` tag or `<div class="center">` but it renders gallery invisible.

Also, is it possible to center align text in slide description?

**Comment by sal0max** [comment]
> is there way to align gallery horizontally on the page? I.e. I have a gallery of just two pictures which doesn't take the full width of the page. I've tried to wrap [gallery] in `<center>` tag or `<div class="center">` but it renders gallery invisible.

That's possible. Just use `[gallery lastRow="center"]`

> Also, is it possible to center align text in slide description?

The underlying lightbox is [GLightbox](https://github.com/biati-digital/glightbox). So, it would have to support that feature.
You can check out its options. As far as I can tell, there is no way to center the description.

**Comment by lustyffh** [comment]
> That's possible. Just use `[gallery lastRow="center"]`

Thanks, it works indeed. Just didn't think of that feature this way =). But it works not exactly as I was epxecting. I.e. it properly aligns gallery which otherwise consumed just a single row. However it also tries to sqeeze into a single line the gallery which previously occupied 2-3 rows. I.e. it doesn't seem to align only the bottom row.
